server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /graphics/ {
        alias /usr/share/nginx/html/graphics/;
        expires 1d;
        add_header Cache-Control "public, immutable";
    }

    location /music/ {
        alias /usr/share/nginx/html/music/;
        expires 1d;
        add_header Cache-Control "public, immutable";
    }
}
